### ISSUE TITLE
issue about python setup.py build develop

### ISSUE THREAD

**Issue by hei789** [michelecafagna26/vinvl-visualbackbone#4]
#### ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1516, in _run_ninja_build
    subprocess.run(
  File "/root/miniconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
#### Python  3.8(ubuntu18.04)

**Comment by michelecafagna26** [comment]
It seems something related to your environment. 
best advise I can give you is to check the compatibility of your CUDA drivers with your pytorch version (and related dependencies)
